<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[3,4,4,6],[7,8,9,9],[8,1,1,3]],dtype=np.float128)

In [ ]:
a[1]

array([7., 8., 9., 9.], dtype=float128)

In [ ]:
a.dtype

dtype('float128')

In [ ]:
a.itemsize

16

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 4)

In [ ]:
a.size

12

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
a=np.linspace(1,5,10)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.itemsize

8

In [ ]:
a.size

10

In [ ]:
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
a


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
a=np.array([[3,4,4,6],[7,8,9,9],[8,1,1,3]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.reshape(4,3)

array([[3, 4, 4],
       [6, 7, 8],
       [9, 9, 8],
       [1, 1, 3]])

In [ ]:
a.reshape(2,6)

array([[3, 4, 4, 6, 7, 8],
       [9, 9, 8, 1, 1, 3]])

In [ ]:
a

array([[3, 4, 4, 6],
       [7, 8, 9, 9],
       [8, 1, 1, 3]])

In [ ]:
a.ravel()

array([3, 4, 4, 6, 7, 8, 9, 9, 8, 1, 1, 3])

In [ ]:
a


array([[3, 4, 4, 6],
       [7, 8, 9, 9],
       [8, 1, 1, 3]])

In [ ]:
a.sum()

np.int64(63)

In [ ]:
a.min()

np.int64(1)

In [ ]:
a.max()

np.int64(9)

In [ ]:
a.sum(axis=0)

array([18, 13, 14, 18])

In [ ]:
a.sum(axis=1)

array([17, 33, 13])

In [ ]:
np.sqrt(a)

array([[1.73205081, 2.        , 2.        , 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.        ],
       [2.82842712, 1.        , 1.        , 1.73205081]])

In [ ]:
a

array([[3, 4, 4, 6],
       [7, 8, 9, 9],
       [8, 1, 1, 3]])

In [ ]:
b=np.array([[1,0],[2,1]])

In [ ]:
b

array([[1, 0],
       [2, 1]])

In [ ]:
c=np.array([[5,0],[1,1]])

In [ ]:
b+c

array([[6, 0],
       [3, 2]])

In [ ]:
b.dot(c)

array([[ 5,  0],
       [11,  1]])