<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/numpy(indexing%2Cslicing%2Cstacking).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,7,8],[9,8,7],[1,1,1]])

In [3]:
a

array([[1, 7, 8],
       [9, 8, 7],
       [1, 1, 1]])

In [4]:
a[1,2]

np.int64(7)

In [5]:
a[0:2,2]

array([8, 7])

In [8]:
a[0:3,2]

array([8, 7, 1])

In [9]:
a[-1]

array([1, 1, 1])

In [10]:
a[-1,2]

np.int64(1)

In [11]:
a[-1,0:3]

array([1, 1, 1])

In [12]:
for row in a:
  print(row)

[1 7 8]
[9 8 7]
[1 1 1]


In [18]:
for row in a.flatten():
  print(row)

1
7
8
9
8
7
1
1
1


In [19]:
a

array([[1, 7, 8],
       [9, 8, 7],
       [1, 1, 1]])

In [20]:
b=np.arange(9).reshape(3,3)

In [21]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.vstack((a,b))

array([[1, 7, 8],
       [9, 8, 7],
       [1, 1, 1],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.hstack((a,b))

array([[1, 7, 8, 0, 1, 2],
       [9, 8, 7, 3, 4, 5],
       [1, 1, 1, 6, 7, 8]])

In [29]:
c=np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
split=np.hsplit(c,3)

In [31]:
split

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [36]:
a

array([[1, 7, 8],
       [9, 8, 7],
       [1, 1, 1]])

In [34]:
split=np.vsplit(c,2)
split

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [35]:
b=a>4
b

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [37]:
a[b]

array([7, 8, 9, 8, 7])