<a href="https://colab.research.google.com/github/sangeerthP-10/my_works/blob/main/numpy(nditer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(3,4)

In [3]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
for row in a:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [8]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
for cell in a.ravel():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
for cell in np.nditer(a,order='C'):
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
for cell in np.nditer(a,order='f'):
  print(cell)

0
4
8
1
5
9
2
6
10
3
7
11


In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
for x in np.nditer(a,order='f', flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [32]:
for x in np.nditer(a,order='f', op_flags=['readwrite']):
  x[...]=x*x


In [33]:
a

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [34]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [39]:

for x,y in np.nditer([a,b]):
  print(x*y)

0
3
768
19683
458752
2734375
11757312
40353607
184549376
473513931
1100000000
2357947691


In [ ]:
sum=0
for x,y in np.nditer([a,b]):

  sum+=x*y
print(sum)